[31337]
endpoint_url = "http://anvil:8545"

[31338]
endpoint_url = "http://anvil-settlement:8546"

[1234567890]
endpoint_url = ""
keyRegistry = 31337
votingPowerProvider = [31337]
settlement = [
    31337,
    31338,
]
valSetDriver = 31337
